[package]
name = "newyears"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
crossterm  = "0.22.1"
chrono = "0.4"
figlet-rs = "0.1.3"
